sudo: required

language: bash

services:
  - docker

env:
  - DIR_2_BUILD=lighttpd IMAGE_NAME=lighttpd IMAGE_VERSION=1.4.52
  - DIR_2_BUILD=sonar-lts IMAGE_NAME=sonar-lts IMAGE_FLAVORS="base java js" IMAGE_VERSION=6.7.6

# before_script:


script:
  - cd "${DIR_2_BUILD}"
  - pwd & ls -la
  - BASEDIR=$(dirname "$0")
  - export BASEDIR=$(readlink -f $BASEDIR)
  - export BASENAME=$(basename $BASEDIR)
  - export DIR_CHANGE=$(git log --name-status HEAD^..HEAD | cat | grep $BASENAME >/dev/null 2>&1)
  - export IMAGE_NAME=${DIR_2_BUILD}
  - export IMAGE_SVERSION=$(echo ${IMAGE_VERSION} | cut -d'.' -f1,2)
  - make build
  - make version-tag
  - make images
  - make test

deploy:
  provider: script
  script: echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin && make push
  on:
    branch: master

notifications:
  email: 
    on_success: change # default: change
    on_failure: always # default: always
