sudo: required

language: bash

services:
  - docker

env:
  - DIR_2_BUILD=lighttpd, IMAGE_NAME=lighttpd, IMAGE_VERSION=1.4.52
  # - IMAGE_2_BUILD=sonar-lts

before_script:
  - cd "${DIR_2_BUILD}"
  - BASEDIR=$(dirname "$0")
  - export BASEDIR=$(readlink -f $BASEDIR)
  - export BASENAME=$(basename $BASEDIR)
  - export DIR_CHANGE=$(git log --name-status HEAD^..HEAD | cat | grep $BASENAME >/dev/null 2>&1)
  - export IMAGE_NAME=${DIR_2_BUILD}
  - export IMAGE_VERSION
  - export IMAGE_SVERSION=$(echo ${IMAGE_VERSION} | cut -d'.' -f1,2)
  - export DOCKER_USER=${DOCKER_USER:-castocolina}

script:
  - make build
  - make images
  - make test

# before_deploy:
#   provider: script
#   script: make version-tag && echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin
#   on:
#     branch: master

# deploy:
#   provider: script
#   script: make push
#   on:
#     branch: master

# after_success:
#   - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
#       make version-tag
#       echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin
#       make push;
#     fi

# notifications:
#   email: false
